name: Main
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name : Install Dependencies
        run : npm install --ignore-scripts
      - name : Bootstrap Dependencies
        run : npx lerna bootstrap --no-ci
      - name : Run Tests
        run : npm run test
        env:
          CI: true

  build_docker:
    name: Build docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name : Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layer
        uses: actions/cache@v2
        with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.INTEG_TEST_AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.INTEG_TEST_AWS_KEY_SECRET }}
          aws-region: us-west-2
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build image and push to ECR
        uses: docker/build-push-action@v2
        with:
          file: integ-test/js-sdk-emitter/Dockerfile
          context: .
          tags: 611364707713.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-otel-js-sample-app:${{ github.sha }}
          push: true
          
  run_app_test_framework:
    runs-on: ubuntu-latest
    needs: [build_docker]
    steps:
      - name: Setup and Run Otel collector
        run: |
          docker-compose -f .github/collector/docker-compose.yml up &
          env:
            ACCESS_KEY: ${{ secrets.INTEG_TEST_AWS_KEY_ID }}
            SECRET_ACCESS_KEY: ${{ secrets.INTEG_TEST_AWS_KEY_SECRET }}

      - name: Run Http App with Instrumentation
        run: |
          docker run -e AWS_ACCESS_KEY_ID=${{ secrets.INTEG_TEST_AWS_KEY_ID }} \
                     -e AWS_SECRET_ACCESS_KEY=${{ secrets.INTEG_TEST_AWS_KEY_SECRET }} \
                     -e AWS_REGION=us-west-2 \
                     -e INSTANCE_ID=${{ github.run_id }}-${{ github.run_number }} \
                     -e LISTEN_ADDRESS=0.0.0.0:8080 \
                     -e OTEL_EXPORTER_OTLP_ENDPOINT=172.17.0.1:55680 \
                     -e OTEL_EXPORTER_OTLP_INSECURE=True \
                     -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/otel-test/${{ matrix.instrumentation-type}}-instrumentation/${{ matrix.app-platform }}:${{ github.sha }} &
      
      - name: Directory to checkout test framework
        run: mkdir test-framework 

      - name: Checkout test framework
        uses: actions/checkout@v2
        with:
          repository: aws-observability/aws-otel-test-framework
          ref: terraform
          path: test-framework

      // TODO (kkelvinlo) Once OpenTelemetry-JS updates issues about semantic convention for attributes to map to int or collector-contrib 
      // handles doubles use standard data template
       - name: Run testing suite
         run: ./gradlew :validator:run --args='-c temporary-otel-js-trace-metric-validation.yml --endpoint http://127.0.0.1:8080 --metric-namespace -t ${{ github.run_id }}-${{ github.run_number }}'
         env:
          AWS_ACCESS_KEY_ID: ${{ secrets.INTEG_TEST_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.INTEG_TEST_AWS_KEY_SECRET }}
          AWS_REGION: us-west-2
        working-directory: test-framework
